# Generated by Django 5.2.7 on 2025-11-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelMember',
        ),
    ]
