# Generated by Django 5.2.7 on 2025-11-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Member', '0004_delete_modelmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho', models.CharField(max_length=255)),
                ('ten', models.CharField(max_length=255)),
                ('codeforces_id', models.CharField(max_length=255)),
                ('org', models.CharField(max_length=255)),
            ],
        ),
    ]
